name: Day-07

on:
  workflow_dispatch:
  push:
    paths:
      - '**07*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release --verbose
      - name: Run
        run: time target/release/aoc 07
